function adder_spec

  simout = run_simulation('adder', {
      'time', signal_builder('time'), ...
      'a',    signal_builder('const', 'Value', 5), ...
      'b',    signal_builder('const', 'Value', 2), ...
    }, {} ...
  );

  expect(all(simout.c == 7));

end
